services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./wealthwise-backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
      - mysql
    volumes:
      - ./wealthwise-backend/.env:/app/.env:ro

  frontend:
    build: ./wealthwise-frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  redis_data:
  mongo_data:
  mysql_data:
