version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build: ./wealthwise-backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./wealthwise-backend/.env:/app/.env:ro

  frontend:
    build: ./wealthwise-frontend
    container_name: frontend_container
    ports:
      - "80:80"
    # Remove these mounts; Dockerfile already copies build files and nginx.conf
    # volumes:
    #   - ./wealthwise-frontend/build:/usr/share/nginx/html:ro
    #   - ./wealthwise-frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  redis_data:
