services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file:
      - ./wealthwise-backend/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  backend:
    build: ./wealthwise-backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./wealthwise-backend/.env:/app/.env:ro

  frontend:
    build: ./wealthwise-frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  redis_data:
